## Numpy Assignment
Student Name: MUBANGIZI AMBROSE

## Instructions:
- Please complete the questions below.
- for each cell, complete it with good essays and code examples
- Please comment your code indicating how you approached the problem

# What is NumPy, and what are some of its key features?


NumPy (Numerical Python) is a powerful open-source library for numerical computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a large collection of mathematical functions to operate on these arrays efficiently.


Key Features:
Efficient storage and manipulation of numerical arrays.

Vectorized operations (avoiding slow Python loops).

Broadcasting capabilities to perform arithmetic on arrays of different shapes.

Integration with C/C++/Fortran for high-performance computations.

Useful functions for linear algebra, Fourier transform, statistics, and random number generation.

# How do you create a NumPy array using Python's built-in range() function?


We can convert a Python range into a NumPy array using np.array() or np.arange().

In [1]:
import numpy as np

# Using range() and np.array()
arr1 = np.array(range(0, 10))
print("Using range():", arr1)

# Or using np.arange(), which is more direct
arr2 = np.arange(0, 10)
print("Using np.arange():", arr2)


Using range(): [0 1 2 3 4 5 6 7 8 9]
Using np.arange(): [0 1 2 3 4 5 6 7 8 9]


# What is the difference between a scalar value and a vector in NumPy?
with code example

A scalar is a single number (0-dimensional array).

A vector is a 1-dimensional array of numbers.

In [2]:
scalar = np.array(5)  # scalar
print("Scalar:", scalar, "| Shape:", scalar.shape)

vector = np.array([1, 2, 3])  # vector
print("Vector:", vector, "| Shape:", vector.shape)


Scalar: 5 | Shape: ()
Vector: [1 2 3] | Shape: (3,)


# How do you calculate the mean of a NumPy array using the mean() function?

Examples 



The mean() function computes the average of array elements.

In [3]:
arr = np.array([10, 20, 30, 40, 50])
mean_val = np.mean(arr)
print("Mean of the array:", mean_val)


Mean of the array: 30.0


# What is broadcasting in NumPy, and how can it be useful?


Broadcasting allows NumPy to perform operations on arrays of different shapes without copying data. It expands smaller arrays so they match the shape of larger arrays during arithmetic operations.

Example

In [4]:
a = np.array([1, 2, 3])
b = 5  # scalar

# Broadcasting b to match shape of a
result = a + b
print("Broadcasting result:", result)


Broadcasting result: [6 7 8]


# How can you slice a NumPy array to extract a subarray?




Slicing allows access to sub-parts of an array using start:stop:step syntax.

Example

In [5]:
arr = np.array([10, 20, 30, 40, 50])
sub_arr = arr[1:4]  # Elements at index 1, 2, 3
print("Sliced subarray:", sub_arr)


Sliced subarray: [20 30 40]


# What are some of the available functions for performing element-wise operations on NumPy arrays?


Common element-wise operations:
np.add(), np.subtract(), np.multiply(), np.divide()

np.sqrt(), np.square(), np.exp(), np.log()

Example

In [6]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", np.add(a, b))
print("Square root:", np.sqrt(a))


Addition: [5 7 9]
Square root: [1.         1.41421356 1.73205081]


# How do you reshape a NumPy array to have a different shape?





Using reshape() to change the dimensions of an array.

Example

In [7]:
arr = np.arange(12)  # 1D array with 12 elements
reshaped = arr.reshape(3, 4)  # 3 rows, 4 columns
print("Reshaped array:\n", reshaped)


Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# How do you perform matrix multiplication on two NumPy arrays using the dot() function?


Example

In [8]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

product = np.dot(A, B)
print("Matrix multiplication:\n", product)


Matrix multiplication:
 [[19 22]
 [43 50]]


# How can you use the where() function to apply a condition to a NumPy array?


The np.where() function returns elements or indices based on a condition.

Example

In [9]:
arr = np.array([10, 15, 20, 25, 30])

# Replace values greater than 20 with 100
new_arr = np.where(arr > 20, 100, arr)
print("Conditionally replaced array:", new_arr)


Conditionally replaced array: [ 10  15  20 100 100]


# What is the difference between the flatten() and ravel() functions in NumPy?




flatten() returns a copy of the array (changes don’t affect original).

ravel() returns a view (modifying it may change the original array).

In [10]:
arr = np.array([[1, 2], [3, 4]])

flat = arr.flatten()
rvl = arr.ravel()

print("Flatten:", flat)
print("Ravel:", rvl)


Flatten: [1 2 3 4]
Ravel: [1 2 3 4]


# How do you use NumPy's advanced indexing capabilities to select specific elements from an array?


Use lists or arrays of indices for fancy indexing.

In [11]:
arr = np.array([10, 20, 30, 40, 50])

# Select elements at index 1, 3, and 4
indices = [1, 3, 4]
selected = arr[indices]
print("Selected elements:", selected)


Selected elements: [20 40 50]


# How can you use NumPy's broadcasting rules to perform operations on arrays with different shapes?

If shapes are compatible, NumPy broadcasts smaller arrays to match larger ones during operations.

In [12]:
A = np.array([[1], [2], [3]])  # Shape (3,1)
B = np.array([10, 20, 30])     # Shape (3,)

# Broadcasting: A expands to (3,3), B reshapes implicitly
result = A + B
print("Broadcasted addition:\n", result)


Broadcasted addition:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


### Project: Array Statistics Calculator
**Description:**

In this project, you will create a program that allows a user to enter a list of numbers, and then calculates and displays various statistics about those numbers using NumPy.

**Requirements:**

- The program should prompt the user to enter a list of numbers separated by commas.
- The program should use NumPy to convert the input into a 1D NumPy array.
- The program should calculate and display the following statistics:
- The mean of the numbers
- The median of the numbers
- The standard deviation of the numbers
- The maximum and minimum values of the numbers
- The program should use appropriate NumPy functions to calculate the statistics.
- The program should display the statistics with appropriate labels.

### Sample Output
```
Enter a list of numbers separated by commas: 2, 5, 7, 3, 1, 9
Statistics for the input array:
Mean: 4.5
Median: 4.0
Standard Deviation: 2.9154759474226504
Maximum: 9
Minimum: 1
```

In [13]:
import numpy as np

# Prompt the user for input
user_input = input("Enter a list of numbers separated by commas: ")

# Split the input string into a list of strings, then convert to float and make a NumPy array
numbers = np.array([float(num.strip()) for num in user_input.split(',')])

# Calculate statistics using NumPy functions
mean_value = np.mean(numbers)
median_value = np.median(numbers)
std_deviation = np.std(numbers)
max_value = np.max(numbers)
min_value = np.min(numbers)

# Display the results
print("\nStatistics for the input array:")
print(f"Mean: {mean_value}")
print(f"Median: {median_value}")
print(f"Standard Deviation: {std_deviation}")
print(f"Maximum: {max_value}")
print(f"Minimum: {min_value}")



Statistics for the input array:
Mean: 5.4
Median: 6.0
Standard Deviation: 2.5768197453450252
Maximum: 9.0
Minimum: 2.0
